const promptSummary = `Resuma o seguinte texto das legendas de um vídeo e formate o resumo em Markdown, utilizando cabeçalhos para os tópicos principais, se aplicável, e listas de pontos-chave.  \n- O título principal (representado pelo '# ' ou '## ') deve ser apenas o tema principal do vídeo, sem incluir termos como "Resumo de" ou "Resumo do vídeo".  \n- Na introdução, mencione o tom e a linguagem usados no vídeo (por exemplo, formal, informal).  \n- Utilize uma estrutura adequada ao conteúdo: \n- Para vídeos com múltiplos tópicos, utilize divisões por cabeçalhos.  \n  - Para vídeos lineares, utilize uma lista de pontos.  \n  - Para vídeos extensos, utilize subtópicos.\n- Ao final, inclua uma conclusão que destaque:  \n  - As mensagens passadas no vídeo.  \n  - A mensagem principal do vídeo.  \n  - A conclusão que o próprio vídeo apresenta, se houver.  \n  - Estruture essa conclusão em tópicos como uma lista.  \n\nLegendas:`;
const promptAnalysis = `# Instruções para Análise\nAnalise as legendas do vídeo fornecidas abaixo e elabore um resumo estruturado em Markdown que capture a essência do conteúdo. Siga estas diretrizes específicas:\n## Estrutura do Resumo\n\n### Título Principal\n- Use formato # Título com apenas o tema central do vídeo\nEvite termos como "Resumo de" ou "Análise sobre"\nO título deve ser conciso e representativo do conteúdo principal\n\n### Introdução\n- Contextualize brevemente o assunto do vídeo\n- Identifique o tom e registro linguístico (formal, informal, técnico, coloquial)\n- Indique o público-alvo aparente do conteúdo\n- Mencione o formato de apresentação (entrevista, aula, narrativa, etc.)\n\n### Corpo do Resumo (escolha o formato mais adequado)\n- Para conteúdos com múltiplos tópicos distintos:\n  - Use cabeçalhos secundários (## Tópico) para cada seção principal\n  - Para cada tópico, liste 3-5 pontos-chave em formato de marcadores\n- Para conteúdos lineares/narrativos:\n  - Use uma lista sequencial numerada dos principais acontecimentos ou argumentos\n  - Mantenha a ordem cronológica ou lógica do vídeo\n- Para conteúdos extensos ou complexos:\n  - Use subtópicos (### Subtópico)\n\nPara conteúdos extensos ou complexos:\n\n- Combine cabeçalhos principais com subcabeçalhos (### Subtópico)\n- Organize hierarquicamente as informações\n- Use citações diretas (>) para frases impactantes ou conclusões importantes\n\n### Elementos Adicionais a Identificar\n\n- Termos técnicos ou conceitos-chave (em negrito)\n- Dados numéricos ou estatísticos relevantes (em itálico)\n- Referências a outras fontes, estudos ou pessoas mencionadas\n- Momentos de transição importantes no discurso\n\n### Conclusão\n\n- Liste as mensagens principais transmitidas no vídeo\n- Identifique a conclusão central ou propósito do conteúdo\n- Destaque eventuais chamadas para ação ou reflexões finais propostas\n- Formate como lista de marcadores para facilitar a leitura\n\n## Análise Contextual\nAlém do resumo estruturado, inclua uma breve seção final com:\n\n- Análise do Discurso: Identifique padrões linguísticos, estratégias retóricas ou elementos persuasivos utilizados\n- Consistência: Avalie se há contradições ou mudanças de posicionamento ao longo do conteúdo\n- Elementos Subjetivos: Identifique opiniões pessoais versus informações baseadas em fatos\n- Lacunas: Mencione tópicos relevantes que foram omitidos ou pouco explorados\n\nA 'Análise Contextual' é um breve análise sobre as estratégias discursivas, consistência e eventuais vieses identificados no conteúdo\n\nLegendas: `;
const promptTranscript = `Você vai receber uma transcrição bruta do YouTube sem pontuação, sem parágrafos e com possíveis erros de palavras. Corrija os erros de forma sutil, mantendo o máximo possível das palavras originais e o sentido da frase. Adicione pontuação e parágrafos de maneira coerente e concisa, mas não altere significativamente as palavras ou a estrutura original, apenas o necessário para a compreensão.

Caso tenha mais de uma pessoa falando, separe e identifique cada falante. Por exemplo, em um vídeo de React, identifique como "Youtuber: ..." e "Vídeo: ...". Se o Youtuber se identificar com o nome dele, use o nome em vez de 'Youtuber'. Tente descobrir ou adivinhar quem está falando em cada sentença, principalmente em debates ou transcrições de vídeos informativos.

A resposta deve conter somente a transcrição corrigida, com a identificação dos falantes, pontuação e parágrafos organizados, sem nenhum adicional ou explicação.\n\nTranscrição: `;
const prompts = {
  promptAnalysis,
  promptSummary,
  promptTranscript,
};

export default prompts;
